[sprint-2/step-1] - added burger constructor context and make order api call
DimaDemyanov/react-burger pull request #3
Opened 2023-01-19 02:56 UTC by DimaDemyanov

2023-01-19 04:07 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется контекст;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В компоненте App-header требуется поправить семантику, переделать div в ссылки.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной  компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: https://disk.yandex.com/i/HU9XejBBrEzcDg;

- по чек-листу файл контекста должен быть в папке `/services`;

- Исправьте ошибку в консоли при открытии модального окна: https://disk.yandex.com/i/iTiUQc9wRjQbSQ;

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-01-19 04:07 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +const MAKE_ORDER_URL = 'https://norma.nomoreparties.space/api/orders';
**Надо исправить**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/orders`

2023-01-19 04:07 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
>      ingredient: INGREDIENT_TYPE
**Надо исправить:**

Не забывайте указывать isRequired для пропсов, без этого не контролируется что пропс передаётся.

2023-01-19 04:07 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
>      let bun = ingredients.find(ingredient => ingredient.type === 'bun');
**Надо исправить:**

если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2023-01-19 04:07 UTC, ArslanMustafin commented on src/App.tsx
>  const API_URL = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:**

Похожее замечание в burger-constructor

2023-01-19 04:07 UTC, ArslanMustafin commented on src/App.tsx
> +          </BurgerConstructorContext.Provider >
**Надо исправить:**

Вынесите начальный стейт контекста в отдельную переменную.
burger-ingredients не использует этот контекст, поэтому оборачивать компонент не нужно.

2023-01-19 04:07 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
>  const MainIngredient = ({ ingredient }) =>
**Можно лучше:**

Лучше вынести в отдельный компонент.

2023-01-22 02:02 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
>  const MainIngredient = ({ ingredient }) =>
Вынес

2023-01-22 02:10 UTC, DimaDemyanov commented on src/App.tsx
> +          </BurgerConstructorContext.Provider >
Сделал

2023-01-22 02:38 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
> +const MAKE_ORDER_URL = 'https://norma.nomoreparties.space/api/orders';
Вынес

2023-01-22 02:39 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
>      ingredient: INGREDIENT_TYPE
Добавил

2023-01-22 02:40 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
>      let bun = ingredients.find(ingredient => ingredient.type === 'bun');
Исправил

2023-01-22 02:40 UTC, DimaDemyanov commented on src/App.tsx
>  const API_URL = 'https://norma.nomoreparties.space/api/ingredients';
Исправил

2023-01-24 05:30 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### Вы молодец! Работа принята, удачи в дальнейшем обучении

- Практически замечания с прошлого ревью были исправлены;

### Но есть несколько новых замечаний, которые нужно исправить к следующей работе

- В компоненте App-header нужно поправить внешний вид ссылок, в соответствии с макетом: <https://disk.yandex.com/i/pToYrueOc3_vzg>.

- У вас не совсем правильное оформление модального окна `order-details`, фон и иконка должны быть другими.
  - как у вас: <https://disk.yandex.com/i/dcXLZ1lp2Neblw>;
  - как в макете: <https://disk.yandex.com/i/JJx6p-bTI7E1RA>;

- Старайтесь не использовать `git push --force`, это может очень сильно осложнить "жизнь" ревьюеру) если у вас возникли какие-то проблемы с гитом, то лучше обратиться к наставнику/ментору.

- <https://disk.yandex.com/i/xf5JLRd7esz-dg> - нужно исправить зацикленность запроса.

### _Подробно эти и более мелкие замечания, отмечены в коде._

2023-01-24 05:30 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  }, [ingredients]);
**Надо исправить:**

<https://disk.yandex.com/i/xf5JLRd7esz-dg> - нужно исправить зацикленность запроса. Она возникает, из-за `ingredients` в зависимостях у `useEffect`. Чтобы запрос отправлялся 1 раз (2 раза если strict mode) нужно использовать пустой массив зависимостей.

2023-01-24 05:30 UTC, ArslanDev666 approved these changes

2023-01-24 12:04 UTC, merged