[sprint-2/step-2] - Redux & DND added
DimaDemyanov/react-burger pull request #4
Opened 2023-02-26 23:22 UTC by DimaDemyanov

2023-02-27 05:49 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/NIWxroNaMuklwA>, <https://disk.yandex.com/i/HC5_c31UkCDTlg> - по макету, вроде бы, другой цвет фона должен быть;

- <https://disk.yandex.com/i/GSRGGcGwvcW99Q> - нужно поменять цвет текста, на такой же, как у иконки.

- <https://disk.yandex.com/i/VTm8gabX7ZufAA> - вам нужно учитывать стоимость 2 булок, при подсечёте итоговой цены заказа;

- Нужно запретить нажатие кнопки, если пользователь выбрал только ингредиенты <https://disk.yandex.com/i/eSuOQHutXo3EGA>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/rzCvkF6NV73UjQ>, а также чтобы в массиве были только `id` ингредиентов;

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

- Со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  <https://redux.js.org/api/combinereducers>

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-27 05:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        [...ingredients, bun, "60d3b41abdacab0026a733c9"]
**Надо исправить:**

Тут не должно быть захардкоженных данных.

2023-02-27 05:49 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +
**Можно лучше:**

Работать с DOM элементами лучше по ref. Т.е. использовать хук `useRef`.

2023-02-27 05:49 UTC, ArslanDev666 commented on src/services/actions/index.js
> +      })
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше  разместить их в отдельном файле  `utils/burger-api.js`

Например:

```js

const NORMA_API = `https://norma.nomoreparties.space/api`;

export function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(checkResponse )
}

export function sendOrder(data) {
   return fetch(`${NORMA_API}/orders`)
    .then(checkResponse )
}

```

, а не описывать запросы в самом компоненте

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-02-27 05:49 UTC, ArslanDev666 commented on src/services/actions/index.js
> +export function getIngredients(url) {
**Надо исправить:**

Здесь и в другом запросе.

Экшен не должен знать про url.

2023-02-27 05:49 UTC, ArslanDev666 commented on src/services/actions/index.js
> +        console.log(response);
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-27 05:49 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +let currId = 0;
**Надо исправить:**

Тут лучше использовать специальную библиотеку, например `uuid`. И генерировать id. нужно в `action-creator`.

2023-02-27 05:49 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +          { ...action.ingredient, id: currId++ },
**Надо исправить:**

редьюсер должен быть чистой функции, сейчас при каждом вызове добавления ингредиента результат будет отличаться, даже если стейт и экшен одинаковые - будет генерироваться каждый раз новый id,  при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене, а не генерировать в редьюсере. Иначе это делает редьюсер не чистой функцией, что нарушает правило редьюсеров

2023-02-28 01:08 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
> +        [...ingredients, bun, "60d3b41abdacab0026a733c9"]
Убрал

2023-02-28 01:38 UTC, DimaDemyanov commented on src/components/burger-ingredients/burger-ingredients.jsx
> +
Исправил

2023-02-28 02:00 UTC, DimaDemyanov commented on src/services/actions/index.js
> +export function getIngredients(url) {
Исправил

2023-02-28 02:00 UTC, DimaDemyanov commented on src/services/actions/index.js
> +      })
Исправил

2023-02-28 02:02 UTC, DimaDemyanov commented on src/services/actions/index.js
> +        console.log(response);
Убрал console.log()

2023-02-28 02:07 UTC, DimaDemyanov commented on src/services/reducers/index.js
> +let currId = 0;
Исправил

2023-02-28 02:07 UTC, DimaDemyanov commented on src/services/reducers/index.js
> +          { ...action.ingredient, id: currId++ },
Исправил

2023-02-28 05:22 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но ещё есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/71ocaYD8oRU35Q> - вам также нужно учитывать стоимость ингредиентов, при подсечёте итоговой цены заказа. Т.е. учитываем и булки и ингредиенты;

- Если перенести только ингредиент, то приложение падает: <https://disk.yandex.com/i/ftflqVi-H0n2_g>;

- Иконка не соответствует макету:
  - как у вас: <https://disk.yandex.com/i/atSDjrqw1h0T9Q>;
  - как в макете: <https://disk.yandex.com/i/E6ehLpPa1ikeQA>;

2023-02-28 05:22 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    await dispatch(
**Можно лучше:**

`await` тут не влияет на результат

2023-02-28 05:22 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +      dispatch({ type: ADD_CONSTRUCTOR_INGREDIENT, ingredient, id: uuidv4() });
**Можно лучше:**

генерировать id лучше в `action-creator` функции)) Это делается для того, чтобы при добавлении ещё 1 способа переноса ингредиента в конструктор, вы не забыли присвоить этому ингредиенту уникальный идентификатор.

2023-02-28 21:09 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
> +    await dispatch(
Убрал

2023-02-28 22:39 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.jsx
> +      dispatch({ type: ADD_CONSTRUCTOR_INGREDIENT, ingredient, id: uuidv4() });
Исправил

2023-03-01 05:39 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец🔥! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-15 15:08 UTC, merged