sprint-3/step-1 - Routing added
DimaDemyanov/react-burger pull request #6
Opened 2023-04-15 15:09 UTC by DimaDemyanov

2023-04-17 04:00 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- У вас возникает ошибка при запуске приложения: <https://disk.yandex.com/i/noZGq6UmjuPv8Q>. Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте;

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`;

- Нужно поправить вёрстку, на всех страницах авторизации, сдвинуть контент на середину экрана <https://disk.yandex.com/i/in4k0rSXKMidIw>, <https://disk.yandex.com/i/yyyO-hDZ5mdgWQ> и т.д;

- Нужно исправить ошибку при открытии модального окна ингредиента: <https://disk.yandex.com/i/cvTUpdHJ7oz7jA>;

- Нужно исправить ошибки при открытии страницы профиля `/profile`: <https://disk.yandex.com/i/9MJeM9yyjmOwbQ>;

- Вы должны использовать компонент `Link` из `react-router`, а не обычную ссылку, проверьте во всём проекте;

- При перезагрузке страницы авторизированный, пользователь должен оставаться в системе, а не проходить авторизацию заново;

- По чек-листу, требуется реализовать:

  - При клике по ингредиенту происходит переход на маршрут /ingredients/:id и открывается модальное окно с описанием ингредиента. При прямом переходе на этот маршрут открывается страница с информацией об ингредиенте. Прошу обратить внимание на запрос `GET - /ingredients` (получение ингредиентов), его лучше делать всего 1 раз, в компоненте `app`;

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

  - При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее.

  - Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
    При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
    При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.
    <https://disk.yandex.com/i/gxelKyYFeXO5-w>

- Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку;

### **Сделает код лучше:**

- оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

  ```js
  <>
    <div>.....</div>
    <div>.....</div>
  </>
  ```

  <https://ru.reactjs.org/docs/fragments.html>

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/app/App.jsx
> +  }, [authChecked, dispatch]);
**Надо исправить:**

у вас по 2 раза вызываются запросы, из-за проверки, лучше вынести её в отдельный `useState`. https://disk.yandex.com/i/5-PlSKvIoBoIeg

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/header/app-header.jsx
>      <a
**Надо исправить:**

Вы должны использовать компонент `Link` из react-router, а не ссылку.

https://reactrouter.com/en/main/components/link

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/header/app-header.jsx
> +  isActive: PropTypes.object,
**Надо исправить:**

В прошлый раз вы правильно указали тип пропса.

`PropTypes.bool`

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/header/app-header.jsx
> +            isActive={isConstructor}
**Надо исправить:**

здесь и далее, вы должны приводить переменную к boolean значению: `ssActive={!!isConstructor}`.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/forgot-password.jsx
> +    <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>

```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/forgot-password.jsx
> +            <Button htmlType="button" type="primary" size="medium" onClick={onClick}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/forgot-password.jsx
> +            <a
**Надо исправить:**

вы должны использовать компонент `Link` из `react-router`.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/login.jsx
> +            onClick={onClick}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/login.jsx
> +    <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/register.jsx
> +  const [password, setPassword] = useState("");
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/register.jsx
> +            <Button htmlType="button" type="primary" size="medium" onClick={onClick}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/reset-password.jsx
> +            <Button htmlType="button" type="primary" size="medium" onClick={onClick}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/pages/reset-password.jsx
> +    <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/profile-info/profile-info.jsx
> +            <Input type="password" placeholder="Пароль" icon={"EditIcon"} value={user.password} />
**Надо исправить:**

нету у  объекта `user` поля `password`.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/profile-link/profile-link.jsx
> +  }
**Надо исправить:**

передайте просто ещё 1 пропс `href` например, и тогда не нужно будет делать какие-либо проверки.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/components/utils/protected-route.jsx
> +  if (!isLoggedIn && !onlyUnAuth) {
**Надо исправить:**

`isLoggedIn`, нужно проверять отдельно. Иначе у вас любой пользователь будет перенаправлен на `/login`.

2023-04-17 04:00 UTC, ArslanDev666 commented on src/utils/burger-api.js
> +  return await request(`${BURGER_BASE_API}/orders`, {
**Надо исправить:**

тут тоже нужно использовать `requestWithRefresh`

2023-04-19 18:05 UTC, DimaDemyanov commented on src/components/header/app-header.jsx
> +  isActive: PropTypes.object,
Исправил обратно

2023-04-19 18:06 UTC, DimaDemyanov commented on src/components/header/app-header.jsx
> +            isActive={isConstructor}
Добавил приведение, но в другом месте

2023-04-19 18:07 UTC, DimaDemyanov commented on src/components/pages/reset-password.jsx
> +    <>
Убрал

2023-04-19 18:07 UTC, DimaDemyanov commented on src/components/profile-info/profile-info.jsx
> +            <Input type="password" placeholder="Пароль" icon={"EditIcon"} value={user.password} />
Исправил

2023-04-19 18:16 UTC, DimaDemyanov commented on src/components/profile-link/profile-link.jsx
> +  }
Сделал

2023-04-19 19:10 UTC, DimaDemyanov commented on src/components/app/App.jsx
> +  }, [authChecked, dispatch]);
Сделал вот так, надеюсь вы это имели в виду

```  const [authChecked, ] = useState(useSelector(state => state.auth || state.auth.authChecked)); ```

2023-04-19 19:29 UTC, DimaDemyanov commented on src/components/header/app-header.jsx
>      <a
Сделал

2023-04-19 19:31 UTC, DimaDemyanov commented on src/components/pages/forgot-password.jsx
> +    <>
Убрал

2023-04-19 19:50 UTC, DimaDemyanov commented on src/utils/burger-api.js
> +  return await request(`${BURGER_BASE_API}/orders`, {
Исправил

2023-04-20 06:19 UTC, ArslanDev666 commented on src/components/utils/protected-route.jsx
> +  if (!isLoggedIn && !onlyUnAuth) {
**Надо исправить:**

Лучше написать вот так), тогда пользователь не будет видеть те страницы, которые ему не положены.

```js
if (!isLoggedIn) {
    return <>Loading...</>;
  }

  if (!user && !onlyUnAuth) {
    return <Navigate to={'/login'} replace state={{ from: location }} />;
  }

  if (onlyUnAuth && user) {
    return <Navigate to={from} />;
  }
```

2023-04-20 06:19 UTC, ArslanDev666 commented on src/components/app/App.jsx
> +  }, [authChecked, dispatch]);
Не совсем, извините тут моя ошибка, я имел ввиду `useEffect`.

```js
  const authChecked = useSelector(state => state.auth.authChecked);

  useEffect(() => {
    dispatch(getIngredients());
    dispatch(getUser());
  }, [dispatch]);

  useEffect(() => {
    if (authChecked) {
      setLoading(false);
    }
  }, [authChecked]);
```

и верните как было)) там конечно же не нужен такой `useState`) Выше написал правильный вариант.

2023-04-20 06:25 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Все замечания с прошлого ревью были исправлены;

### **Но есть ещё пару небольших замечаний, которые нужно исправить:**

- У `useForm.js`, тоже нужно изменить расширение на `.jsx`;

- У вас 2 раза вызывается запрос на пользователя, а должен вызываться только 1 раз, отметил в коде как это исправить.

2023-04-20 06:25 UTC, ArslanDev666 commented on src/utils/burger-api.js
> +    return res.catch();
**Надо исправить:**

вот именно из-за этого и происходит двойной запрос, даже когда всё ОК))

2023-04-20 10:00 UTC, DimaDemyanov commented on src/components/utils/protected-route.jsx
> +  if (!isLoggedIn && !onlyUnAuth) {
Эта версия у меня не заработала... Показывает Loading на странице, но не перенаправляет на другую страницу. Исправил в роутинг в App.

2023-04-20 10:17 UTC, DimaDemyanov commented on src/components/app/App.jsx
> +  }, [authChecked, dispatch]);
Исправил

2023-04-20 23:09 UTC, DimaDemyanov commented on src/utils/burger-api.js
> +    return res.catch();
Исправил

2023-04-21 07:01 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-21 07:01 UTC, ArslanDev666 commented on src/components/utils/protected-route.jsx
> +  if (!isLoggedIn && !onlyUnAuth) {
Не работает, т.к. isLoggedIn - true, у вас в случае успешного логина, а при ошибке он у вас false, лучше тоже сделать true, чтобы понимать, прошёл ли пользователь этап авторизации (не важно, успешно или нет), а сам результат определять по наличию `user`.

2023-04-21 16:11 UTC, merged