[sprint-4/step-1] - Convert JavaScript to TypeScript
DimaDemyanov/react-burger pull request #7
Opened 2023-04-22 18:25 UTC by DimaDemyanov

2023-04-25 04:19 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил замечания в коде;

### **Сделает код лучше:**

- Старайтесь не использовать `any` без необходимости. `any` - по сути отключает типизацию полностью.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-04-25 04:19 UTC, ArslanMustafin commented on src/index.tsx
> +
**Можно лучше:**

Начиная с 17-ой строчки.

Лучше создать файл `store.ts` в папке `services`, и вынести это туда.

2023-04-25 04:19 UTC, ArslanMustafin commented on src/index.tsx
> +export type AppDispatch = ThunkDispatch<RootState, any, AnyAction>;
**Вы молодец.:**

Круто, что вы сразу, хоть и не весь, но начали типизировать `redux`. Главное потом не забудьте правильно типизировать `useSelector`

2023-04-25 04:19 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +  const [, dropTarget] = useDrop<any>({
**Надо исправить:**

Вместо `any` тут должен быть вот такой тип `{ingredient:TIngredient}`

2023-04-25 04:19 UTC, ArslanMustafin commented on src/components/burger-constructor/main-ingredient.tsx
> +  const [{ handlerId }, drop] = useDrop<any, any, any>({
**Надо исправить:**

Тут тоже не должно быть `any`,

в идеале вам нужно написать вот так 

```ts
  import { Identifier } from "dnd-core";

  const ... = useDrop<
      {
        ingredient: TIngredient;
        index: number;
      },
      unknown,
      { handlerId: Identifier | null }
    >
  ```

  Но т.к. тянуть ещё 1 библиотеку не всегда хочется, то можно написать просто `any`.

  ```ts
  const ... = useDrop<
    {
      ingredient: TIngredient;
      index: number;
    },
    unknown,
    any
  >
  ```

2023-04-25 04:19 UTC, ArslanDev666 commented on src/services/actions/auth.ts
> +  return function (dispatch: ThunkDispatch<{}, {}, AnyAction>) {
**Можно лучше:**

Здесь и далее.

Тут не нужно дополнительно типизировать `dispatch`, т.к. вы выше уже типизировали его.

2023-04-25 04:19 UTC, ArslanDev666 commented on src/utils/burger-api.ts
> +const checkResponse = (res: Response): Promise<any> => {
**Надо исправить:**

Для типизации `checkResponse`, вам нужно использовать дженерики.

```ts
const checkResponse = <T>(res: Response): Promise<T> => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

// Пример
export const getIngredients = () => {
  return fetch(`${BURGER_API_URL}/ingredients`)
    .then((res) => checkResponse<TIngredientsResponse>(res)).then(...)
};
```

2023-04-25 04:19 UTC, ArslanDev666 commented on src/utils/burger-api.ts
> +export const requestWithRefresh = async (url: string, options: RequestInit): Promise<any> => {
**Надо исправить:**

тут тоже не нужно использовать `any`, и вообще лучше не указывать тип возвращаемого значения.

Используйте дженерик, чтобы в дальнейшем правильно типизировать `request`.

```ts
export const fetchWithRefresh = async <T>(
  url: RequestInfo,
  options: RequestInit
) => {
  //...
  return await checkResponse<T>(res);
  //...
}
```

2023-04-25 04:19 UTC, ArslanDev666 commented on src/utils/burger-api.ts
> +async function request(url: string, options?: RequestInit) {
**Надо исправить:**

тут тоже лучше использовать дженерики)

```ts
async function request<T>(url: string, options?: RequestInit): Promise<T> {...}
```

2023-04-25 04:19 UTC, ArslanDev666 commented on src/utils/burger-api.ts
> +export const getIngredientsRequest = async (): Promise<any> => {
**Надо исправить:**

Здесь и далее. (После исправлений с дженериками)

Вы должны указать правильно тип для дженерика `request` или `requestWithRefresh`. а возвращаемый тип `Promise<any>`, можно будет удалить.

А также не нужно везде писать `return await request(..)`, `await` тут лишний (Его по крайней мере не принято писать. Но если углубиться в V8, то с await будет чуть лучше).

И плюс если в функции нет ни одного await, то async ей тоже не нужен

2023-04-25 19:14 UTC, DimaDemyanov commented on src/index.tsx
> +
Исправил

2023-04-25 19:16 UTC, DimaDemyanov commented on src/components/burger-constructor/burger-constructor.tsx
> +  const [, dropTarget] = useDrop<any>({
Исправил

2023-04-25 19:18 UTC, DimaDemyanov commented on src/components/burger-constructor/main-ingredient.tsx
> +  const [{ handlerId }, drop] = useDrop<any, any, any>({
исправил

2023-04-25 19:23 UTC, DimaDemyanov commented on src/services/actions/auth.ts
> +  return function (dispatch: ThunkDispatch<{}, {}, AnyAction>) {
Убрал типизацию

2023-04-25 20:51 UTC, DimaDemyanov commented on src/utils/burger-api.ts
> +const checkResponse = (res: Response): Promise<any> => {
Исправил

2023-04-25 20:51 UTC, DimaDemyanov commented on src/utils/burger-api.ts
> +export const requestWithRefresh = async (url: string, options: RequestInit): Promise<any> => {
Исправил

2023-04-25 20:51 UTC, DimaDemyanov commented on src/utils/burger-api.ts
> +async function request(url: string, options?: RequestInit) {
Исправил

2023-04-25 20:51 UTC, DimaDemyanov commented on src/utils/burger-api.ts
> +export const getIngredientsRequest = async (): Promise<any> => {
Исправил

2023-04-26 04:37 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-30 17:40 UTC, merged